# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pip install pytest
    pip install pytest-azurepipelines
    pip install pytest-cov
    pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
  displayName: 'Test with pytest'

- script : |
    pip install pycodestyle
    pip install pydocstyle
    pip install pyflakes
    python -m pycodestyle --max-line-length 90 hydrate/*.py
    python -m pydocstyle hydrate/*.py
    python -m pyflakes hydrate/*.py
    python -m pycodestyle --max-line-length 90 tests/*.py
    python -m pydocstyle tests/*.py
    python -m pyflakes tests/*.py
  displayName: 'CSE linting packages (pycodestyle, pydocstyle, pyflakes)'

- task: Docker@2
  inputs:
    containerRegistry: 'hydrate-acr'
    repository: 'hydrate'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'hydrate-$(Build.SourceBranchName)-$(Build.BuildId)'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/test-*.xml'
    testRunTitle: 'Publish test results for Python $(python.version)'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'